name: Autopep8

on:
  push:
    branches:
      - main  # Cambia "main" por el nombre de la rama principal de tu repositorio

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Cambia "3.x" por la versión de Python que estés utilizando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run Autopep8
      run: |
        autopep8 --in-place --recursive .

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -a -m "Apply autopep8 formatting"
        git push
